### ISSUE TITLE
Error in console: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by abhilashlr** [kellyselden/ember-cli-update#69] opened 2017-08-15 09:00 UTC
When ember-cli-update is run from the ember project folder, the following error is thrown:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): You must start with a clean working directory

node version: 6.11.1

**Comment by rwjblue** [comment] 2017-08-15 12:22
See the conversation in https://github.com/kellyselden/ember-cli-update/issues/64 for details, but the tool expects that `git status` shows that there are no uncommitted changes in the repo before it will begin attempting the update.

**Comment by kellyselden** [comment] 2017-08-15 16:57
Duplicate of #65.

Thanks for filing.

**Closed by kellyselden** 2017-08-15 16:57 UTC
