### ISSUE TITLE
Git repo put into a bad state after ".git/index.lock: File exists." errors

### ISSUE THREAD

**Issue by dwickern** [kellyselden/ember-cli-update#112] opened 2017-09-07 16:44 UTC
```
dwickern:ui dwickern$ ember-cli-update --ignore-conflicts
Cloning into bare repository '/var/folders/dz/4bq_l12j3491zyx7g8vk6nr80000gn/T/tmp-6689NVfjU3YWGjuY/.git'...
Switched to a new branch '3bccf3c0-93e9-11e7-b21b-ab3e637caecb'
Note: checking out 'f98da31d2299050773c98e01b1019437cd323391'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f98da31... 2.14.0
fatal: Unable to create '/Users/dwickern/code/my-app/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
{ Error: Command failed: git add -A
fatal: Unable to create '/Users/dwickern/code/my-app/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

...

dwickern:ui dwickern$ git show
fatal: your current branch '3bccf3c0-93e9-11e7-b21b-ab3e637caecb' does not have any commits yet
dwickern:ui dwickern$ git status
On branch 3bccf3c0-93e9-11e7-b21b-ab3e637caecb

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	./

nothing added to commit but untracked files present (use "git add" to track)
```
Recovered with `git checkout --force master`

**Comment by vlascik** [comment] 2017-09-07 22:00
I can confirm this, it happened while I had the same repo open in SourceTree.

**Comment by dwickern** [comment] 2017-09-07 22:02
Forgot to mention I had sourcetree open as well

**Comment by kellyselden** [comment] 2017-09-07 22:02
While I don't know if we can continue if SourceTree has a lock on the repo, we can recover the error better. That branch `3bccf3c0-93e9-11e7-b21b-ab3e637caecb` you were left in is an expected part of the process, so we can catch the error, delete that temp branch and put you back to where you were.

**Comment by dwickern** [comment] 2017-09-07 22:04
Any recovery steps you take might run into the same problem though

**Comment by kellyselden** [comment] 2017-09-07 22:14
very true

**Comment by dwickern** [comment] 2017-09-07 22:20
My understanding is you generate a patch from the two ember-cli versions and apply it. Does it need to change the working directory at all? That can cause trouble for sourcetree and editors, especially for larger projects

**Comment by kellyselden** [comment] 2017-09-09 03:59
Can you try again with the new version v0.6.6? It should still error because of SourceTree, but I added recovery so your repo should go back to a clean state. Running via `DEBUG=ember-cli-update,git-diff-apply ember-cli-update` will give you a lot more info.

**Comment by kellyselden** [comment] 2017-09-13 02:14
Closing as you shouldn't be left in a bad state anymore.

**Closed by kellyselden** 2017-09-13 02:14 UTC
