### ISSUE TITLE
Deletes all files from custom .gitignored folders

### ISSUE THREAD

**Issue by vlascik** [kellyselden/ember-cli-update#237] opened 2017-12-13 17:15 UTC
After `ember-cli-update` almost all of the files in custom .gitignored folders were deleted for some reason. Some random files and subfolders were left behind. 

```
P:\Project>set DEBUG=ember-cli-update,git-diff-apply && ember-cli-update
  ember-cli-update npm info ember-cli versions --json +0ms
  ember-cli-update [
  ember-cli-update   "0.0.0",
...
  ember-cli-update   "2.16.0-beta.1",
  ember-cli-update   "2.16.0-beta.2",
  ember-cli-update   "2.16.0",
  ember-cli-update   "2.16.1",
  ember-cli-update   "2.16.2",
  ember-cli-update   "2.17.0-beta.1",
  ember-cli-update   "2.17.0-beta.2",
  ember-cli-update   "2.17.0",
  ember-cli-update   "2.17.1",
  ember-cli-update   "2.18.0-beta.1"
  ember-cli-update ]
  ember-cli-update  +3s
  ember-cli-update npm info ember-cli@latest version --json +55ms
  ember-cli-update "2.17.1"
  ember-cli-update  +2s
  git-diff-apply git status --porcelain +0ms
  git-diff-apply  +81ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-new-output C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git +2ms
Cloning into bare repository 'C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git'...
  git-diff-apply  +2s
  git-diff-apply git --git-dir="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git" rev-parse v2.16.0-beta.1 +1ms
  git-diff-apply a8a94452823e4a0b7a7e92403088369179e30dff
  git-diff-apply  +74ms
  git-diff-apply git --git-dir="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git" --work-tree="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz" checkout a8a94452823e4a0b7a7e92403088369179e30dff +0ms
Note: checking out 'a8a94452823e4a0b7a7e92403088369179e30dff'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a8a9445... 2.16.0-beta.1
  git-diff-apply  +133ms
  git-diff-apply git --git-dir="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git" rev-parse v2.17.1 +4ms
  git-diff-apply 90ade7c5cbb928d4d2a688c20bfedb5bb135ff15
  git-diff-apply  +66ms
  git-diff-apply git --git-dir="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git" --work-tree="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz" checkout 90ade7c5cbb928d4d2a688c20bfedb5bb135ff15 +1ms
Previous HEAD position was a8a9445... 2.16.0-beta.1
HEAD is now at 90ade7c... 2.17.1
  git-diff-apply  +115ms
  git-diff-apply git rev-parse --show-toplevel +1ms
  git-diff-apply P:/Project
  git-diff-apply  +66ms
  git-diff-apply git --git-dir="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git" rev-parse v2.16.0-beta.1 +0ms
  git-diff-apply a8a94452823e4a0b7a7e92403088369179e30dff
  git-diff-apply  +66ms
  git-diff-apply git --git-dir="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git" --work-tree="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz" checkout a8a94452823e4a0b7a7e92403088369179e30dff +1ms
Previous HEAD position was 90ade7c... 2.17.1
HEAD is now at a8a9445... 2.16.0-beta.1
  git-diff-apply  +104ms
  git-diff-apply chdir P:/Project +0ms
  git-diff-apply git symbolic-ref --short HEAD +1ms
  git-diff-apply update-2.16-beta.1
  git-diff-apply  +67ms
  git-diff-apply git checkout --orphan 8a818d00-e024-11e7-87bc-51e4e00ef064 +1ms
Switched to a new branch '8a818d00-e024-11e7-87bc-51e4e00ef064'
  git-diff-apply  +102ms
  git-diff-apply git reset --hard +0ms
  git-diff-apply  +341ms
  git-diff-apply ensureDirSync P:\Project +512ms
  git-diff-apply chdir P:\Project +1ms
  git-diff-apply [ '.editorconfig',
  git-diff-apply   '.ember-cli',
  git-diff-apply   '.eslintrc.js',
  git-diff-apply   '.git',
  git-diff-apply   '.gitignore',
  git-diff-apply   '.travis.yml',
  git-diff-apply   '.watchmanconfig',
  git-diff-apply   'app',
  git-diff-apply   'config',
  git-diff-apply   'ember-cli-build.js',
  git-diff-apply   'package.json',
  git-diff-apply   'public',
  git-diff-apply   'README.md',
  git-diff-apply   'testem.js',
  git-diff-apply   'tests',
  git-diff-apply   'vendor' ] +0ms
  git-diff-apply copy C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz P:\Project +6ms
  git-diff-apply git add -A +45ms
warning: LF will be replaced by CRLF in !!!!!!bak/ember-cli-copyable/.bowerrc.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in !!!!!!bak/ember-cli-copyable/.editorconfig.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in !!!!!!bak/ember-cli-copyable/.ember-cli.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in !!!!!!bak/ember-cli-copyable/.gitignore.
The file will have its original line endings in your working directory.
... same thing for each file in custom folders...


  git-diff-apply  +697ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply A  !!!!!!bak/bower_components/jquery-ui/ui/.DS_Store
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/.bowerrc
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/.editorconfig
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/.ember-cli
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/.gitignore
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/.jshintrc
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/.npmignore
...
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/tests/index.html
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/tests/test-helper.js
  git-diff-apply A  !!!!!!bak/ember-cli-copyable/vendor/.gitkeep
  git-diff-apply AM !!!!!!bak/ember-cli-deploy-ssh2--
  git-diff-apply A  !!!!!!bak/ember-cli-dotenv/.editorconfig
  git-diff-apply A  !!!!!!bak/ember-cli-dotenv/.ember-cli
  git-diff-apply A  !!!!!!bak/ember-cli-dotenv/.env
...
  git-diff-apply A  !!!!!!bak/ember-cli-fastboot/vendor/.gitkeep
  git-diff-apply A  !!!!!!bak/ember-cli-fastboot/yarn.lock
  git-diff-apply AM !!!!!!bak/ember-cli-icheck----
  git-diff-apply A  !!!!!!bak/ember-cli-ion-rangeslider----/node_modules/broccoli-merge-trees/CHANGELOG.md
...
  git-diff-apply A  !!!!!!bak/ember-theme-changer/package.json
  git-diff-apply AM "!!!!!!bak/linked packages bak/ember-cart"
  git-diff-apply AM "!!!!!!bak/linked packages bak/ember-cli-icheck"
  git-diff-apply AM "!!!!!!bak/linked packages bak/ember-cli-ion-rangeslider"
  git-diff-apply A  .editorconfig
  git-diff-apply A  .ember-cli
  git-diff-apply A  .eslintrc.js
  git-diff-apply A  .gitignore
  git-diff-apply A  .travis.yml
  git-diff-apply A  .watchmanconfig
  git-diff-apply A  README.md
  git-diff-apply A  app/app.js
  git-diff-apply A  app/components/.gitkeep
  git-diff-apply A  app/controllers/.gitkeep
  git-diff-apply A  app/helpers/.gitkeep
  git-diff-apply A  app/index.html
  git-diff-apply A  app/models/.gitkeep
  git-diff-apply A  app/resolver.js
  git-diff-apply A  app/router.js
  git-diff-apply A  app/routes/.gitkeep
  git-diff-apply A  app/styles/app.css
  git-diff-apply A  app/templates/application.hbs
  git-diff-apply A  app/templates/components/.gitkeep
  git-diff-apply A  config/environment.js
  git-diff-apply A  config/targets.js
  git-diff-apply A  ember-cli-build.js
  git-diff-apply A  package.json
  git-diff-apply A  public/crossdomain.xml
  git-diff-apply A  public/robots.txt
  git-diff-apply A  testem.js
  git-diff-apply A  tests/.eslintrc.js
  git-diff-apply A  tests/helpers/destroy-app.js
  git-diff-apply A  tests/helpers/module-for-acceptance.js
  git-diff-apply A  tests/helpers/resolver.js
  git-diff-apply A  tests/helpers/start-app.js
  git-diff-apply A  tests/index.html
  git-diff-apply A  tests/integration/.gitkeep
  git-diff-apply A  tests/test-helper.js
  git-diff-apply A  tests/unit/.gitkeep
  git-diff-apply A  vendor/.gitkeep
  git-diff-apply  +281ms
  git-diff-apply git commit -m "message" +76ms
  git-diff-apply [8a818d00-e024-11e7-87bc-51e4e00ef064 (root-commit) 9bed6a9] message
  git-diff-apply  358 files changed, 21428 insertions(+)
  git-diff-apply  create mode 100644 !!!!!!bak/bower_components/jquery-ui/ui/.DS_Store
  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-copyable/.bowerrc
  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-copyable/.editorconfig
  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-copyable/.ember-cli
  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-copyable/.gitignore
  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-copyable/.jshintrc
  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-copyable/.npmignore
  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-copyable/.travis.yml

  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-fastboot/yarn.lock
  git-diff-apply  create mode 160000 !!!!!!bak/ember-cli-icheck----
  git-diff-apply  create mode 100644 !!!!!!bak/ember-cli-ion-rangeslider----/node_modules/broccoli-merge-trees/CHANGELOG.md
...
  git-diff-apply  create mode 100644 !!!!!!bak/ember-theme-changer/jsconfig.json
  git-diff-apply  create mode 100644 !!!!!!bak/ember-theme-changer/package.json
  git-diff-apply  create mode 160000 !!!!!!bak/linked packages bak/ember-cart
  git-diff-apply  create mode 160000 !!!!!!bak/linked packages bak/ember-cli-icheck
  git-diff-apply  create mode 160000 !!!!!!bak/linked packages bak/ember-cli-ion-rangeslider
  git-diff-apply  create mode 100644 .editorconfig
  git-diff-apply  create mode 100644 .ember-cli
  git-diff-apply  create mode 100644 .eslintrc.js
  git-diff-apply  create mode 100644 .gitignore
  git-diff-apply  create mode 100644 .travis.yml
  git-diff-apply  create mode 100644 .watchmanconfig
  git-diff-apply  create mode 100644 README.md
  git-diff-apply  create mode 100644 app/app.js
  git-diff-apply  create mode 100644 app/components/.gitkeep
  git-diff-apply  create mode 100644 app/controllers/.gitkeep
  git-diff-apply  create mode 100644 app/helpers/.gitkeep
  git-diff-apply  create mode 100644 app/index.html
  git-diff-apply  create mode 100644 app/models/.gitkeep
  git-diff-apply  create mode 100644 app/resolver.js
  git-diff-apply  create mode 100644 app/router.js
  git-diff-apply  create mode 100644 app/routes/.gitkeep
  git-diff-apply  create mode 100644 app/styles/app.css
  git-diff-apply  create mode 100644 app/templates/application.hbs
  git-diff-apply  create mode 100644 app/templates/components/.gitkeep
  git-diff-apply  create mode 100644 config/environment.js
  git-diff-apply  create mode 100644 config/targets.js
  git-diff-apply  create mode 100644 ember-cli-build.js
  git-diff-apply  create mode 100644 package.json
  git-diff-apply  create mode 100644 public/crossdomain.xml
  git-diff-apply  create mode 100644 public/robots.txt
  git-diff-apply  create mode 100644 testem.js
  git-diff-apply  create mode 100644 tests/.eslintrc.js
  git-diff-apply  create mode 100644 tests/helpers/destroy-app.js
  git-diff-apply  create mode 100644 tests/helpers/module-for-acceptance.js
  git-diff-apply  create mode 100644 tests/helpers/resolver.js
  git-diff-apply  create mode 100644 tests/helpers/start-app.js
  git-diff-apply  create mode 100644 tests/index.html
  git-diff-apply  create mode 100644 tests/integration/.gitkeep
  git-diff-apply  create mode 100644 tests/test-helper.js
  git-diff-apply  create mode 100644 tests/unit/.gitkeep
  git-diff-apply  create mode 100644 vendor/.gitkeep
  git-diff-apply  +560ms
  git-diff-apply git --git-dir="C:\Users\z\AppData\Local\Temp\tmp-5848d47PczPeBLFz\.git" diff v2.16.0-beta.1 v2.17.1 > C:\Users\z\AppData\Local\Temp\tmp-58481uYM4GNzFpO7\file.patch +79ms
  git-diff-apply  +72ms
  git-diff-apply git apply C:\Users\z\AppData\Local\Temp\tmp-58481uYM4GNzFpO7\file.patch +1ms
  git-diff-apply  +75ms
  git-diff-apply git checkout -- package.json +1ms
  git-diff-apply  +71ms
  git-diff-apply git status --porcelain +1ms
  git-diff-apply  M !!!!!!bak/ember-cli-deploy-ssh2--
  git-diff-apply  M !!!!!!bak/ember-cli-icheck----
  git-diff-apply  M "!!!!!!bak/linked packages bak/ember-cart"
  git-diff-apply  M .travis.yml
  git-diff-apply  M README.md
  git-diff-apply  M testem.js
  git-diff-apply  D tests/helpers/resolver.js
  git-diff-apply  M tests/test-helper.js
  git-diff-apply  +280ms
  git-diff-apply git add -A +2ms
  git-diff-apply  +292ms
  git-diff-apply git status --porcelain +1ms
  git-diff-apply  M !!!!!!bak/ember-cli-deploy-ssh2--
  git-diff-apply  M !!!!!!bak/ember-cli-icheck----
  git-diff-apply  M "!!!!!!bak/linked packages bak/ember-cart"
  git-diff-apply  M "!!!!!!bak/linked packages bak/ember-cli-icheck"
  git-diff-apply  M "!!!!!!bak/linked packages bak/ember-cli-ion-rangeslider"
  git-diff-apply M  .travis.yml
  git-diff-apply M  README.md
  git-diff-apply M  testem.js
  git-diff-apply D  tests/helpers/resolver.js
  git-diff-apply M  tests/test-helper.js
  git-diff-apply  +284ms
  git-diff-apply git commit -m "message" +2ms
  git-diff-apply [8a818d00-e024-11e7-87bc-51e4e00ef064 d0aebe0] message
  git-diff-apply  5 files changed, 20 insertions(+), 24 deletions(-)
  git-diff-apply  delete mode 100644 tests/helpers/resolver.js
  git-diff-apply  +100ms
  git-diff-apply git rev-parse HEAD +1ms
  git-diff-apply d0aebe098e9b475f91e7d570b3bbfba6e37c363a
  git-diff-apply  +64ms
  git-diff-apply git checkout update-2.16-beta.1 +1ms
warning: unable to rmdir !!!!!!bak/ember-cli-deploy-ssh2--: Directory not empty
warning: unable to rmdir !!!!!!bak/ember-cli-icheck----: Directory not empty
warning: unable to rmdir !!!!!!bak/linked packages bak/ember-cart: Directory not empty
warning: unable to rmdir !!!!!!bak/linked packages bak/ember-cli-icheck: Directory not empty
warning: unable to rmdir !!!!!!bak/linked packages bak/ember-cli-ion-rangeslider: Directory not empty
Switched to branch 'update-2.16-beta.1'
  git-diff-apply  +873ms
  git-diff-apply git cherry-pick --no-commit d0aebe098e9b475f91e7d570b3bbfba6e37c363a +1ms
error: could not apply d0aebe0... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
  git-diff-apply git branch -D 8a818d00-e024-11e7-87bc-51e4e00ef064 +573ms
  git-diff-apply Deleted branch 8a818d00-e024-11e7-87bc-51e4e00ef064 (was d0aebe0).
  git-diff-apply  +77ms
  ember-cli-update git add package.json +8s
  ember-cli-update  +173ms
```

**Comment by kellyselden** [comment] 2017-12-15 23:12
I'm going to chalk this up to a duplicate of #143 or #212, which I am still looking for help on reproducing/adding failing test/fixing.

**Closed by kellyselden** 2017-12-15 23:12 UTC
